default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: stripe_rails_example_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: stripe_rails_example_test

production:
  url: <%= ENV['DATABASE_URL'] %>

# production:
#   <<: *default
#   database: stripe_rails_example_production
#   username: stripe_rails_example
#   password: <%= ENV['STRIPE_RAILS_EXAMPLE_DATABASE_PASSWORD'] %>
